#!/usr/bin/env bash

################################
#install the required packages
################################

# install node 14.x version and pm2
curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - >> ${PKG_INSTALL_LOG} 2>&1
sudo apt-get install -y nodejs >> ${PKG_INSTALL_LOG} 2>&1
sudo npm install pm2 -g >> ${PKG_INSTALL_LOG} 2>&1

# install the mongo package
wget -qO - https://www.mongodb.org/static/pgp/server-4.0.asc | sudo apt-key add - >> ${PKG_INSTALL_LOG} 2>&1
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list >> ${PKG_INSTALL_LOG} 2>&1
sudo apt-get update >> ${PKG_INSTALL_LOG} 2>&1
sudo apt install mongodb-org -y >> ${PKG_INSTALL_LOG} 2>&1
sudo systemctl start mongod >> ${PKG_INSTALL_LOG} 2>&1
sudo systemctl enable mongod >> ${PKG_INSTALL_LOG} 2>&1
