#!/usr/bin/env bash

#################################
#apache server  configuration
#################################

# RC scripts
export APACHE2_RC_SCRIPT_NAME='apache2'

# Configuration files
export HTTP_CONF_ROOT='/etc/apache2'

# Log directory.
export APACHE2_LOG_DIR='/var/log/apache2'

# PID file
export APACHE2_PID='/var/run/apache2.pid'

# sample config folder name
export APACHE2_SAMPLE_DIR="${SAMPLE_DIR}/apache2"

# Log files.
export APACHE2_LOG_ACCESSLOG="${APACHE2_LOG_DIR}/access.log"
export APACHE2_LOG_ERRORLOG="${APACHE2_LOG_DIR}/error.log"

export HTTP_CONF_DIR_AVAILABLE_CONF="${HTTP_CONF_ROOT}/conf-available"
export HTTP_CONF_DIR_ENABLED_CONF="${HTTP_CONF_ROOT}/conf-enabled"

# Directory used to store all sites. Note: not loaded by default.
export HTTP_CONF_DIR_AVAILABLE_SITES="${HTTP_CONF_ROOT}/sites-available"
# Directory used to store site config files which will be loaded by default.
# Usually we just create a symbol link to file under ${HTTP_CONF_DIR_AVAILABLE_SITES}
export HTTP_CONF_DIR_ENABLED_SITES="${HTTP_CONF_ROOT}/sites-enabled"

export APACHE2_CONF="${HTTP_CONF_ROOT}/apache2.conf"

export SITE_ENABLE="a2ensite"

export APACHE2_CONF_SITE_DEFAULT='000-default.conf'
export APACHE2_CONF_SITE_DEFAULT_SSL='default-ssl.conf'
