#!/usr/bin/env bash

ECHO_INFO "Configure Mongo database server."  

export MONGO_USER="$(${RANDOM_STRING})"
export MONGO_PASSWD="$(${RANDOM_STRING})"
export DATABASE_NAME="$(${RANDOM_STRING})"
export MONGO_PORT="$(${RANDOM_NUMBER})"

mongo  <<EOF
use admin;
db.createUser(
  {
    user: "${MONGO_DB_ADMIN_USER}", 
    pwd: "${MONGO_DB_ADMIN_PASSWD}", 
    roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]
  }
)
EOF

mongo -u ${MONGO_DB_ADMIN_USER} -p ${MONGO_DB_ADMIN_PASSWD} --authenticationDatabase admin  <<EOF
use ${DATABASE_NAME};
db.createUser(
    {
        user: '${MONGO_USER}', 
        pwd: '${MONGO_PASSWD}', 
        roles: [{role: 'readWrite', db: '${DATABASE_NAME}' } ] 
    }
)
EOF

# insert the username , password and port number to backup script file
#sudo sed -i "18 i export MONGO_USER='${MONGO_USER}'" ${mongo_backup_script}
#sudo sed -i "19 i export MONGO_PASSWD='${MONGO_PASSWD}'" ${mongo_backup_script}
#sudo sed -i "20 i export DATABASE_NAMES='${DATABASE_NAME}' " ${mongo_backup_script}
#sudo sed -i "21 i export MONGO_PORT='${MONGO_PORT}' " ${mongo_backup_script}

# add the custom port for mongo and change the 127.0.0.1 IP to 0.0.0.0 for remote connection
sudo sed -i -e "23 s/27017/$MONGO_PORT/g"  /etc/mongod.conf
sudo sed -i -e "24 s/127.0.0.1/0.0.0.0/g"  /etc/mongod.conf
echo "# Your Mongo default port is replaced and current mongo port is $MONGO_PORT "  >>${STATUS_FILE}

# add the security authorization enabled
sudo sed -i -e "31 s/#security:/security:/g" /etc/mongod.conf
sudo sed -i '32 i \ authorization: enabled' /etc/mongod.conf
echo "# Security Authorization is enabled "  >>${STATUS_FILE}

# restart the mongod service
sudo systemctl restart mongod

cat >> ${DB_TIP_FILE} <<EOF
Mongo DB reference : 

Superadmin details : 
          * Username: ${MONGO_DB_ADMIN_USER}
          * Password: ${MONGO_DB_ADMIN_PASSWD}
          * Port:     ${MONGO_PORT}
          * DB_NAME:  admin

command: 

mongo -u ${MONGO_DB_ADMIN_USER} -p --authenticationDatabase admin --port $MONGO_PORT

Password : ${MONGO_DB_ADMIN_PASSWD}

    This is admin login details for mongo database 
##################  INFO: Don't share with developers. #####################

Developer db details : 
          * Username: ${MONGO_USER}
          * Password: ${MONGO_PASSWD}
          * PORT:     ${MONGO_PORT}
          * DB_NAME: ${DATABASE_NAME}

      share the above details to the developers for login the mongo database.

command : 

mongo -u ${MONGO_USER} -p ${MONGO_PASSWD} 65.21.49.84:$MONGO_PORT/${DATABASE_NAME}

mongoURI: "mongodb://${MONGO_USER}:${MONGO_PASSWD}@65.21.49.84:$MONGO_PORT/${DATABASE_NAME}"   --- share this mongo uri to developers

mongodump --host 65.21.49.84 -d ${DATABASE_NAME} --port $MONGO_PORT 

mongorestore --host 65.21.49.84 -d ${DATABASE_NAME} --port $MONGO_PORT 
EOF

# separatly save the db_details for sharing to the developer.
cat >> ${Developer_TIP_FILE} <<EOF
Mongo DB reference : 

Developer db details : 
          * Username: ${MONGO_USER}
          * Password: ${MONGO_PASSWD}
          * PORT:     ${MONGO_PORT}
          * DB_NAME: ${DATABASE_NAME}

      share the above details to the developers for login the mongo database.

commands : 

mongo -u ${MONGO_USER} -p ${MONGO_PASSWD} 65.21.49.84:$MONGO_PORT/${DATABASE_NAME}

mongoURI: "mongodb://${MONGO_USER}:${MONGO_PASSWD}@65.21.49.84:$MONGO_PORT/${DATABASE_NAME}" 
EOF

