#!/usr/bin/env bash

#################################
#apache server  configuration
#################################

# web servers 
export PORT_HTTP="${PORT_HTTP:=80}"
export HTTPS_PORT="${HTTPS_PORT:=443}"


if [ X"${DISTRO}" == X'UBUNTU' ]; then
    # Web data.
    export HTTP_DOCUMENTROOT='/var/www/html'

# Daemon user.
export HTTP_USER='www-data'
export HTTP_GROUP='www-data'

fi

[ X"${WEB_SERVER}" == X'APACHE2' ] && . ${CONFIG_DIR}/apache2