#!/usr/bin/env bash

################################
#install the required packages
################################

#update the repository
sudo apt-get update
sudo apt-get upgrade -y

#Basic required package
sudo apt-get install zip unzip -y
sudo apt-get install curl -y
sudo apt-get install software-properties-common -y

# install the mongo package
wget -qO - https://www.mongodb.org/static/pgp/server-4.0.asc | sudo apt-key add -
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
sudo apt-get update
sudo apt install mongodb-org -y
sudo systemctl start mongod
sudo systemctl enable mongod
